(function(m,G,O,a){a=function(b,d){b=b.getElementsByTagName("script");for(var f=0;f<b.length;f++)if(!b[f].getAttribute("data-parsed")&&b[f].src&&0<b[f].src.indexOf(d)){var a={},g=!1;b[f].src.replace(/([^?=;]+)(=([^;]*))?/g,function(b,d,f,c){g||(g=d);a[d]=c});a.url=g;b[f].setAttribute("data-parsed",!0);delete a[g];return a}return{}}(G,"DoubleSideBar.js");var B=(a.compoundSeqNo?a.bn+"#"+a.compoundSeqNo:a.bn)||m.ADFafbanID,u=m.location.hostname,g=m.top||m,b=g.document,J=b.body,P=a.sticky||1,K=a.ratio||
1,Q=a.fit||1,L=a.scale||1.5,p=a.hide||200,C=a.top||0,M=a.distance||960,q=!1,n=0,y=0;"undefined"!==typeof GujAd&&GujAd.getClient().getContentWidth()&&(q=!0,n=GujAd.getClient().getContentWidth(),y=GujAd.$("body").width()?(GujAd.$("body").width()-n)/2:(m.top.innerWidth-n)/2,M=n);a=m._adform=m._adform||[];a.push([B+"#2.panel",{from:1,position:"liti",sticky:!1}]);a.push([B+"#2.on.init",function(a){var d=O.lib,f=g.Adform.adRegister[B+"#1"];if(f){a=function(){setTimeout(I,200)};var A=function(b,a,c){cssId=
"undefined"!==typeof a?a:"adform-custom";c="undefined"!==typeof c?c:G;d.byId(cssId,c)?(style=d.byId(cssId,c),style.innerHTML=b):(style=c.createElement("style"),style.type="text/css",style.id=cssId,style.styleSheet?style.styleSheet.cssText=b:style.appendChild(c.createTextNode(b)),c.getElementsByTagName("head")[0].appendChild(style))},H=function(){if(P){if(-1<u.indexOf("moviepilot.de")||-1<u.indexOf("gamespilot.de"))C=b.getElementsByClassName("navigation--wrapper")[0].offsetHeight;k=".sidebar-fixed {margin-left:0 !important;}";
v=h&&h.getBoundingClientRect();w=c.getBoundingClientRect();D=e.getBoundingClientRect();xPosOne=h?+v.left+h.offsetWidth:w.left;xPosTwo=h?+v.left-e.offsetWidth:D.left;if(1==q||"true"==q)xPosTwo=y-e.offsetWidth;yPos=g.pageYOffset;yPos>=N?(d.addClass(c,"sidebar-fixed"),d.addClass(e,"sidebar-fixed"),c.style.left=xPosOne+"px",k+=".sidebar-fixed.sidebar-two {left:"+xPosTwo+"px !important;}",k+=".sidebar-fixed {position:fixed; top:"+C+"px !important;}"):(d.addClass(c,"sidebar-fixed"),d.addClass(e,"sidebar-fixed"),
c.style.left=xPosOne+"px",k+=".sidebar-fixed.sidebar-two {left:"+xPosTwo+"px !important;}",k+=".sidebar-fixed {position:fixed; top: 0px !important;}");A(k,"adform-double-sidebar",b)}},I=function(){sidebarScale=L?L:0;var a=g.innerHeight-N,z=f.settings.html.width/sidebarScale,r=f.settings.html.height/sidebarScale,l=t.settings.html.height/sidebarScale;var k=".sidebar-one {margin:0;} .hidebar {display:none !important;}"+(1==K?".sidebar-one {min-width:"+f.settings.html.width/sidebarScale+"px; min-height:"+
r+"px;} .sidebar-two {min-width:"+t.settings.html.width/sidebarScale+"px; min-height:"+t.settings.html.height/sidebarScale+"px;} @media screen and (max-width: 1420px) { #SIMAD_wrapper_skyscraper {max-width: "+f.settings.html.width/sidebarScale+"px;} }":"");k+=Q?".sidebar-one, .sidebar-two {max-height:"+a+"px;}":"";E&&(c.style.marginLeft=-E+"px");xPosOne=h?+v.left+h.offsetWidth:w.left;xPosTwo=h?+v.left-e.offsetWidth:D.left;distance=h?h.offsetWidth:M;widthOne=J.clientWidth-xPosOne;if(1==q||"true"==
q)y="undefined"!==typeof GujAd&&GujAd.$("body").width()?(GujAd.$("body").width()-n)/2:(m.top.innerWidth-n)/2,xPosTwo=y-e.offsetWidth,widthOne=J.clientWidth-xPosOne,distance=n;widthTwo=xPosOne-distance;newWidthTwo=p&&widthTwo<=p?p:widthTwo;0!=K?(a/widthOne<F&&a>=r?(c.style.height=a+"px",c.style.width=a/F+"px"):(c.style.width=widthOne<=z||a<=r?z+"px":widthOne+"px",c.style.height=widthOne<=z||a<=r?r+"px":widthOne*F+"px"),a/widthTwo<x&&a>=l?(e.style.height=a+"px",e.style.width=a/x+"px",newWidthTwo=a/
x):(e.style.height=widthTwo<=p||a<=l?l+"px":widthTwo*x+"px",e.style.width=widthTwo<=p||a<=l?l/x+"px":newWidthTwo+"px",newWidthTwo=a<=l?l/x:newWidthTwo)):(c.style.width=widthOne<=z?z+"px":widthOne+"px",c.style.height=a<=r?r+"px":a+"px",e.style.width=newWidthTwo+"px",e.style.height=a<=l?l+"px":a+"px");widthTwo<=p?d.addClass(e,"hidebar"):d.removeClass(e,"hidebar");d.hasClass(c,"sidebar-fixed")&&(c.style.left=xPosOne+"px");e.style.marginLeft=-(+distance+newWidthTwo)+"px";A(k,"adform-double-sidebar-size",
b);H()},t=this;if(-1<u.indexOf("eatsmarter.de")){var k=".offset {width: 970px;}";A(k,"adform",b)}var c=f.adBox.get("element").parentNode,e=t.adBox.get("element").parentNode,h=function(a){var c=u,e=d.byId("holder",b)||d.byId("contentContainer",b)||d.byId("page",b)||d.byId("main",b)||d.byId("mainHeader",b)||d.byId("wrapper_content",b)||b.getElementsByClassName("centeredDiv")[1]||d.byId("ads-outer",b)||d.byId("header",b)||d.byId("content",b)||b.getElementsByClassName("s1-main-content")[0]||b.getElementsByClassName("s1-content-container")[0]||
b.getElementsByClassName("sp-opener-list")[0]||d.byId("wrapper",b)||b.getElementsByTagName("main")[0]||d.byId("innerWrapper",b);c=c.substring(c.lastIndexOf(".",c.lastIndexOf(".")-1)+1);if(refElem=a[c])prefix=refElem.charAt(0),idClass=refElem.substr(1),e="#"==prefix?d.byId(idClass,b):b.getElementsByClassName(idClass)[0];return e}({"eatsmarter.de":".offset","verivox.de":"#wrapper","prosieben.de":"#main","sat1.de":"#main","autoplenum.de":"#holder","gamestar.de":".centeredDiv","n24.de":"#ads-outer","ran.de":"#main",
"sport1.de":"#ads-outer","wetter.com":"#page","sixx.de":"#main","gamepro.de":".centeredDiv","gesundheit.de":"#contentContainer","serienjunkies.de":"#ads-outer","moviepilot.de":"#page","promipool.de":"#ads-outer","gamespilot.de":"#ads-outer","kabeleins.de":"#main","321kochen.tv":"#wrapper_content","bundesliga.de":"#page","onlinewelten.com":"#main","songtexte.com":"#main","tier.tv":"#ads-outer","stern.de":".page__content","chefkoch.de":"#page-wrapper","brigitte.de":".main-wrapper","arcor.de":".pContent",
"seniorbook.de":".wrapper","sportal.de":"#Content"}),v=h&&h.getBoundingClientRect();c.style.display="block";e.style.display="block";var w=c.getBoundingClientRect(),D=e.getBoundingClientRect();u.indexOf("stern.de");var N=+w.top+g.pageYOffset+parseInt(C,10),E=h?w.left-(+v.left+h.offsetWidth):0;if(1==q||"true"==q)E=w.left-(+y+n);var F=f.settings.html.height/f.settings.html.width,x=t.settings.html.height/t.settings.html.width;d.addClass(c,"sidebar-one");d.addClass(e,"sidebar-two");-1===u.indexOf("verivox.de")&&
(p=160);d.addEvent(g,"resize",I);d.addEvent(g,"resize",a);d.addEvent(g,"scroll",H);d.addEvent(g,"scroll",a);a()}}])})(window,document,Adform=window.Adform||{});
